spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/test


  flyway:
    enabled: false # default: true
